### ISSUE TITLE
Work with emscripten?

### ISSUE THREAD

**Issue by prsolucoes** [kallisti5/guisan#14]
Hi,

Work with emscripten (web assembly)?

It need support opengl_es_2

Thanks.

**Comment by kallisti5** [comment]
Currently we target SDL and SDL2 with C / C++ linkages.   I'm not 100% sure how this would work.

SDL is a critical piece of the codebase, and I feel like adding support for web assembly backend drawing would also mean us redoing all of the API's for web assembly.

Since this is beyond the scope of guisan, i'm going to close this issue. *however*, if you can produce a technical plan on how to implement a web assembly backend and are willing to do the work, please feel free to let me know via a ticket or pull request.
